repos:
  - repo: local
    hooks:
      - id: ts-query-format-fix
        name: Check tree-sitter query formatting
        entry: ts_query_ls format ./queries
        language: system
        pass_filenames: false
        files: '^queries/.*\.scm$'

      - id: ts-query-lint
        name: Lint tree-sitter queries
        entry: ts_query_ls lint ./queries
        language: system
        pass_filenames: false
        files: '^queries/.*\.scm$'
